### ISSUE TITLE
print all json paths

### ISSUE THREAD

**Issue by MissionCritical1** [leavesster/vscode-jsonpath#1]
is there a way for this code to parse through all leaf nodes in the json message and create a list of all of the Json Paths, instead of having to click each key. Output of all json paths in a given json message to an excel file or txt file would be helpful.

**Comment by leavesster** [comment]
> is there a way for this code to parse through all leaf nodes in the json message and create a list of all of the Json Paths, instead of having to click each key. Output of all json paths in a given json message to an excel file or txt file would be helpful.

Thank you for reaching out and for your interest in this project and the time you've taken to share your feedback.

I'd like to let you know that the functionality you've requested is actually present in source code, and the data required is already available. 
But I need sometime to implement this feature. The javascript's source code is in [jsonpath-generator](https://github.com/leavesster/jsonpath-generator/tree/vscode) with svelte, a web framework that isn't part of my daily toolkit.

**Comment by MissionCritical1** [comment]
Thank you for your response! How can i run this code with my .json file? 

I was able to run the svelte demokit with success but i received an error when running the jsonpath-generator folder

**Error below**
PS C:\Users\AidanDelgado.AzureAD\OneDrive - Mission Critical Partners\CODE\MAPPING\jsonpath-generator>npm run dev -- --open

> svelte-app@1.0.0 dev
> rollup -c -w --open 

(node:4432) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
[!] RollupError: Node tried to load your configuration file as CommonJS even though it is likely an ES module. To resolve this, change the extension of your configuration to ".mjs", set "type": "module" in your package.json file or pass the "--bundleConfigAsCjs" flag.

Original error: Cannot use import statement outside a module
https://rollupjs.org/command-line-interface/#bundleconfigascjs
C:\Users\MissionCritical\CODE\MAPPING\jsonpath-generator\rollup.config.js:1  
import svelte from 'rollup-plugin-svelte';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at internalCompileFunction (node:internal/vm:77:18)
    at wrapSafe (node:internal/modules/cjs/loader:1288:20)
    at Module._compile (node:internal/modules/cjs/loader:1340:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at cjsLoader (node:internal/modules/esm/translators:345:17)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:294:7)
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)


**I am able to just do a plan run, but im not sure how to specify my json file**

PS C:\Users\MissionCritical\CODE\MAPPING\jsonpath-generator> npm run
Lifecycle scripts included in svelte-app@1.0.0:
  start
    sirv public --no-clear

available via `npm run-script`:
  build
    rollup -c
  build:vscode
    VSCODE=1 rollup -c
  dev
    rollup -c -w
  check
    svelte-check --tsconfig ./tsconfig.json


Any help would be appreciated! Thank you :)

**Comment by leavesster** [comment]
I've test jsonpath-generator code in both `vscode` and `master` branches,  it works fine in my compute.

`SyntaxError: Cannot use import statement outside a module` this error seems the node treat this js as `cjs` but the code is esm module, this is a poor front-end development experience.

I don't know why it happened in this case. but the I guess you can try to fix by rename `rollup.config.js` to `rollup.config.ts` so that the config file will be translated by typescript. (working in my place)

**Comment by leavesster** [comment]
@MissionCritical1 
hi, I've working on this feature. here is a preview, can you help me to confirm is this you want ?

this is the json.
<img width="309" alt="json" src="https://github.com/leavesster/vscode-jsonpath/assets/11785335/36aa90bc-619f-4a22-a4f6-70c22585570c">

this is this JSONPath list
<img width="688" alt="list" src="https://github.com/leavesster/vscode-jsonpath/assets/11785335/3994bd38-c183-4922-97f3-51fa006a875a">

for now, I'm not sure is the list is enough?

**Comment by MissionCritical1** [comment]
Hi @leavesster This is exactly what i am looking for! Great job, this is awesome! I haven't tried running the code again with your suggestions but I will try soon! Is it possible to update the instructions? Ive had chat gpt write decent instructions before... copy your repo link into chatgpt and it will get you most of the way there on the "how to run" instructions guide.

Will this update be pushed into the current VScode extensions?

**Comment by MissionCritical1** [comment]
I was able to run the code in VSCODE. Im still not sure where or how to access the JSONPath List.

here are my steps:
INSTRUCTIONS FOR VSCODE
1.	Download repository as zip. Extract zip file into desired folder path… example
C:\WORKSPACE\JSON_path_generator
2.	Download VSCODE extension “Svelte for VS Code”
3.	In VSCODE go to file>Open Folder… open file path folder from step 1
4.	Download node.js https://nodejs.org/en
a.	In command line or VSCODE terminal, run “npm install”
b.	verify with ... to check version
c.	node -v
d.	npm -v
e.	https://docs.npmjs.com/downloading-and-installing-node-js-and-npm
f.	“npm audit”
g.	“npm fund”

5.	Run code “npm run dev”
6.	Open local host “   http://localhost:8080”
 
OR
Download VSCODE Extension “JSONPath”
JSONPathv0.0.4
leavesster
generate jsonPath for json

**Comment by leavesster** [comment]
> I was able to run the code in VSCODE. Im still not sure where or how to access the JSONPath List.
> 
> here are my steps: INSTRUCTIONS FOR VSCODE
> 
> 1. Download repository as zip. Extract zip file into desired folder path… example
>    C:\WORKSPACE\JSON_path_generator
> 2. Download VSCODE extension “Svelte for VS Code”
> 3. In VSCODE go to file>Open Folder… open file path folder from step 1
> 4. Download node.js https://nodejs.org/en
>    a.	In command line or VSCODE terminal, run “npm install”
>    b.	verify with ... to check version
>    c.	node -v
>    d.	npm -v
>    e.	https://docs.npmjs.com/downloading-and-installing-node-js-and-npm
>    f.	“npm audit”
>    g.	“npm fund”
> 5. Run code “npm run dev”
> 6. Open local host “   [http://localhost:8080”](http://localhost:8080%E2%80%9D)
> 
> OR Download VSCODE Extension “JSONPath” JSONPathv0.0.4 leavesster generate jsonPath for json

I was push this feature in a different branch, you can click [this link](https://github.com/leavesster/jsonpath-generator/commit/8c28b6bd3ecbc53be0f2413cfc7d6f5863de3617) which I already chose the 'feature' branch for you.

do the same thing you do before , then open http://localhost:8080.
you will see this html like this:

<img width="569" alt="image" src="https://github.com/leavesster/vscode-jsonpath/assets/11785335/95b34696-4b4a-45aa-a1c0-b85360b26d0a">

And sure, it will be published to VSCode extension, but I need some work to make it better for production.

**Comment by MissionCritical1** [comment]
Awesome! I was able to test the current repository (from the link above, branch = feature). In file "jsonpath.ts" line 6 modify to.. "export const showPathList = writable(true);"

I was able to modify file, "main.ts"
![image](https://github.com/leavesster/vscode-jsonpath/assets/153127791/a17fe41d-339c-4c41-b38e-409adf3a0e05)

However, when I input my own validated json the application reads blank. My json is about 1000 lines, its a big message. Is there a run time function/setting I need to modify to allow the system more time to parse through my json message?

**Comment by MissionCritical1** [comment]
The list printed correctly for the smaller json example. 
$.a,$.b,$.c,$.a1.a,$.a1.b,$.a1.c,$.a1.d[0],$.a1.d[1],$.a1.d[2],$.b2[0],$.b2[1],$.b2[2],$.b2[3],$.a1.a,$.a1.b,$.a1.c,$.a1.d[0],$.a1.d[1],$.a1.d[2],$.b2[0],$.b2[1],$.b2[2],$.b2[3],$.a1.a,$.a1.b,$.a1.c,$.a1.d[0],$.a1.d[1],$.a1.d[2],$.b2[0],$.b2[1],$.b2[2],$.b2[3],$.a1.a,$.a1.b,$.a1.c,$.a1.d[0],$.a1.d[1],$.a1.d[2],$.b2[0],$.b2[1],$.b2[2],$.b2[3],$.a1.a,$.a1.b,$.a1.c,$.a1.d[0],$.a1.d[1],$.a1.d[2],$.b2[0],$.b2[1],$.b2[2],$.b2[3],$.a1.a,$.a1.b,$.a1.c,$.a1.d[0],$.a1.d[1],$.a1.d[2],$.b2[0],$.b2[1],$.b2[2],$.b2[3]


To make JSONPaths appear in a list copy "pathList" to excel. 
Step1: Copy string to excel cell A1
Step 2: Navigate to Data tab and select "Text to Columns", select "Comma" Delimiters only, select Destination to be cell A3.
![image](https://github.com/leavesster/vscode-jsonpath/assets/153127791/f9458c94-b732-4283-9d51-7fb869082e44)
Step 3: Select Cell A3 and click and drag all the way to the right to select all cells with values.
Step 4: Copy and Paste Special... "Transpose" in Cell A5
All JSONPaths should now be in a vertical list



![image](https://github.com/leavesster/vscode-jsonpath/assets/153127791/aa8cd3fb-020a-44e9-860c-e3ac45047d19)

**Comment by leavesster** [comment]
> Awesome! I was able to test the current repository (from the link above, branch = feature). In file "jsonpath.ts" line 6 modify to.. "export const showPathList = writable(true);"

wow, I have to commend you on your clever approach. I'm planning to publish to VSCode extension, so I made it configurable.

> However, when I input my own validated json the application reads blank. My json is about 1000 lines, its a big message. Is there a run time function/setting I need to modify to allow the system more time to parse through my json message?

Is the json just cannot show the `pathList` or all content（contain the json tree) become empty?

As far as I know, there is no runtime function can make the system to parse more quick or use more memory. But if the only `jsonpath list` is blank, maybe there is some other optimization I can do. If all content are empty, I need more time to optimize.

be the way how big is your json, 1MiB or more ?  maybe I can test the same size.

**Comment by leavesster** [comment]
Hi, @MissionCritical1 can you give me some information about you json size and is that the most needed ?
If the happens only some edge case, I think maybe we can publish the "show jsonpath list" feature first.

**Comment by MissionCritical1** [comment]
> Is the json just cannot show the pathList or all content（contain the json tree) become empty?

It reads blank, the output is empty.

> be the way how big is your json, 1MiB or more ? maybe I can test the same size.

the file is only 38KB, it could be because its a complicated file, thats not properly defined even though it is well formed and valid. I hand created the example json file and used random values to fill in the data fields.

> Hi, @MissionCritical1 can you give me some information about you json size and is that the most needed ?
If the happens only some edge case, I think maybe we can publish the "show jsonpath list" feature first.

I think your code will work fine, I must have some error somewhere, When i parsed my message into smaller json messages, it worked fine. I truly believe its an error in my message that i created.

**Comment by leavesster** [comment]
> the file is only 38KB, it could be because its a complicated file, thats not properly defined even though it is well formed and valid. I hand created the example json file and used random values to fill in the data fields.
> 
> > Hi, @MissionCritical1 can you give me some information about you json size and is that the most needed ?
> > If the happens only some edge case, I think maybe we can publish the "show jsonpath list" feature first.
> 
> I think your code will work fine, I must have some error somewhere, When i parsed my message into smaller json messages, it worked fine. I truly believe its an error in my message that i created.

OK, I will try to publish a new version at this month. it will support some configuration to show jsonpath list. after configure it in the settings.json, it will show all jsonpath.

And if you not find the error, you can upload your files to this issue, maybe I can help you find out what wrong.

**Comment by leavesster** [comment]
Hi @MissionCritical1 , I've publish 0.0.6 version to support your feature.
you need write:
`"jsonpath.showJsonPathList": true,` on `settings.json` ( if you don't know how to edit , please visit https://code.visualstudio.com/docs/getstarted/settings ).

The UI display may be a bit rough. Once I merge the code for the plugin, I will look for a suitable opportunity to update it.

**Comment by MissionCritical1** [comment]
Hi @leavesster ! Thank you for the updates, I really appreciate your help. UI looks great, I was able to toggle on JsonPathList!

**Follow the steps in image below to toggle on JsonPathList**
![image](https://github.com/leavesster/vscode-jsonpath/assets/153127791/0ba426c7-f405-4860-bd19-fa3f98bdd53e)

### JSONPath VS Code Extension
![image](https://github.com/leavesster/vscode-jsonpath/assets/153127791/dda8c873-4271-40e1-a539-d31787c839bd)

### The JsonPaths are reading incorrectly. 
It seems like the code is reading only a part of the json instance, 4 times and also skipping the first 2 elements. Details below.

**Example JSON Instance (.json)**
`{
	"name": "John Doe",
	"age": 30,
	"address": [
		{
			"street": "123 Main St",
			"city": "New York",
			"state": "NY"
		},
		{
			"street": "123 Main St",
			"city": "New York",
			"state": "NY"
		}
	],
	"hobbies": [
		"reading", "coding", "playing guitar"
	]
}`

**UI Output**
![image](https://github.com/leavesster/vscode-jsonpath/assets/153127791/0d8e8f77-1b1f-4fc4-9488-e2a8f023e53a)

**pathList from UI**
`"pathList": $.a,$.b,$.c,$.a1.a,$.a1.b,$.a1.c,$.b2[0],$.b2[1],$.b2[2],$.address[0].street,$.address[0].city,$.address[0].state,$.address[1].street,$.address[1].city,$.address[1].state,$.hobbies[0],$.hobbies[1],$.hobbies[2],$.address[0].street,$.address[0].city,$.address[0].state,$.address[1].street,$.address[1].city,$.address[1].state,$.hobbies[0],$.hobbies[1],$.hobbies[2],$.address[0].street,$.address[0].city,$.address[0].state,$.address[1].street,$.address[1].city,$.address[1].state,$.hobbies[0],$.hobbies[1],$.hobbies[2],$.address[0].street,$.address[0].city,$.address[0].state,$.address[1].street,$.address[1].city,$.address[1].state,$.hobbies[0],$.hobbies[1],$.hobbies[2],$.address[0].street,$.address[0].city,$.address[0].state,$.address[1].street,$.address[1].city,$.address[1].state,$.hobbies[0],$.hobbies[1],$.hobbies[2],$.address[0].street,$.address[0].city,$.address[0].state,$.address[1].street,$.address[1].city,$.address[1].state,$.hobbies[0],$.hobbies[1],$.hobbies[2],$.address[0].street,$.address[0].city,$.address[0].state,$.address[1].street,$.address[1].city,$.address[1].state,$.hobbies[0],$.hobbies[1],$.hobbies[2],$.hobbies[0],$.hobbies[1],$.hobbies[2],$.address[0].street,$.address[0].city,$.address[0].state,$.address[1].street,$.address[1].city,$.address[1].state,$.hobbies[0],$.hobbies[1],$.hobbies[2],$.address[0].street,$.address[0].city,$.address[0].state,$.address[1].street,$.address[1].city,$.address[1].state,$.hobbies[0],$.hobbies[1],$.hobbies[2],$.address[0].street,$.address[0].city,$.address[0].state,$.address[1].street,$.address[1].city,$.address[1].state,$.hobbies[0],$.hobbies[1],$.hobbies[2],$.address[0].street,$.address[0].city,$.address[0].state,$.address[1].street,$.address[1].city,$.address[1].state,$.hobbies[0],$.hobbies[1],$.hobbies[2]`

**Exported JSONPath List with formatting for visual analysis**
![image](https://github.com/leavesster/vscode-jsonpath/assets/153127791/63320711-c554-4958-99c5-79d1f5deba00)

**Suggest Adding Bilingual Label**
![image](https://github.com/leavesster/vscode-jsonpath/assets/153127791/82b7edbb-3afd-4db1-9a1a-ac642f0e2dd8)
recommend adding "/Collapse" after label text shown in image above

**Is there a new functionality that output generic jsonpaths based on the json structure?**
is that why we have this output path, see below. 
![image](https://github.com/leavesster/vscode-jsonpath/assets/153127791/06521b82-3161-4e58-ab15-162f792c301b)

**Comment by leavesster** [comment]
I'll address these two bugs within this week. While I do provide support for English, it appears to be malfunctioning.

**Comment by leavesster** [comment]
@MissionCritical1 
Version 0.0.7 has been published. It should fix the path list error that occurred when the JSON was changed. I need some time to add support for i18n (multiple languages), so for now I have changed the terminology to use "Collapse" instead.

If you have any other issues, feedback is welcome : )
